# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abfef38489f8976d49fee3c33532301f156271ed76d01f344421dd65ee02bb44c3bd0246ac7bcb21d9cf27ebb27bddf015f9ab8c3319182e7314a2bc03c76682

test:
  secret_key_base: 9bef4c9adeab1ab0096ea02bfb44d992a9c01826914bb1df8ac0864eeb4592c535cd9fb021b85aab6af958057ed49775a627ce8286df513df66d11c123349b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
